M48
; DRILL file {KiCad 8.0.0-8.0.0-1~ubuntu23.10.1} date 2024-02-24T12:52:35+1100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-24T12:52:35+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0-8.0.0-1~ubuntu23.10.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X85.0Y-70.0
X85.0Y-115.0
X235.0Y-70.0
X235.0Y-115.0
M30
